include(ExternalProject)

include(cmake/modules/eigen.cmake)
include(cmake/modules/sophus.cmake)
include(cmake/modules/yaml-cpp.cmake)
include(cmake/modules/gflags.cmake)
include(cmake/modules/glog.cmake)
include(cmake/modules/gtest.cmake)
include(cmake/modules/opengv.cmake)
if(VISUALIZATION)
  include(cmake/modules/pangolin.cmake)
endif()
include(cmake/modules/pybind11.cmake)
include(cmake/modules/cnpy.cmake)
include(cmake/modules/ceres.cmake)
include(cmake/modules/opencv.cmake)
include(cmake/modules/gbenchmark.cmake)
